version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mysql://db:3306/habit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: habit
      MYSQL_ROOT_PASSWORD: 0
    ports:
      - "3306:3306"

volumes:
  jenkins_home:
