version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mysql://db:3306/habit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - db
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: habit
    ports:
      - "3306:3306"
volumes:
  jenkins_home: